import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '../lib/auth-context';

export const metadata: Metadata = {
  metadataBase: new URL('https://kiraguvence.com'),
  title: {
    default: 'SecureLend - Dijital Kira Odeme Platformu | Guvenli Kira Yonetimi',
    template: '%s | SecureLend',
  },
  description:
    'SecureLend ile kiraci, ev sahibi ve banka arasindaki kira odeme surecini guvenle yonetin. Dijital sozlesme, otomatik odeme takibi, KPS kimlik dogrulama ve KMH destegi tek platformda.',
  keywords: [
    'kira odeme',
    'dijital kira',
    'kira guvence',
    'kiraci',
    'ev sahibi',
    'KMH',
    'konut mortgage hesabi',
    'fintech',
    'kira yonetimi',
    'SecureLend',
    'kiraguvence',
    'kira sozlesmesi',
    'online kira odeme',
    'kira takip sistemi',
    'KPS kimlik dogrulama',
    'guvenli kira platformu',
  ],
  authors: [{ name: 'SecureLend' }],
  creator: 'SecureLend',
  publisher: 'SecureLend',
  openGraph: {
    type: 'website',
    locale: 'tr_TR',
    url: 'https://kiraguvence.com',
    siteName: 'SecureLend',
    title: 'SecureLend - Dijital Kira Odeme Platformu',
    description:
      'Kiraci, ev sahibi ve banka arasindaki kira surecini tek merkezde yonetin. Dijital sozlesme, otomatik odeme takibi ve KPS kimlik dogrulama.',
    // OG image auto-generated by opengraph-image.tsx convention
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SecureLend - Dijital Kira Odeme Platformu',
    description:
      'Kiraci, ev sahibi ve banka arasindaki kira surecini tek merkezde yonetin.',
    // Twitter image auto-generated by twitter-image.tsx convention
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://kiraguvence.com',
  },
  other: {
    'theme-color': '#1d4ed8',
    'google-site-verification': '',
  },
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'SecureLend',
  legalName: 'SecureLend Teknoloji',
  url: 'https://kiraguvence.com',
  logo: 'https://kiraguvence.com/opengraph-image',
  description:
    'Dijital kira odeme platformu. Kiraci, ev sahibi ve banka arasindaki sureci tek merkezde yonetir.',
  foundingDate: '2024',
  areaServed: {
    '@type': 'Country',
    name: 'Turkey',
  },
  serviceType: ['Dijital Kira Yonetimi', 'KMH Finansman', 'KPS Kimlik Dogrulama'],
  contactPoint: [
    {
      '@type': 'ContactPoint',
      email: 'info@kiraguvence.com',
      contactType: 'customer service',
      availableLanguage: 'Turkish',
    },
    {
      '@type': 'ContactPoint',
      email: 'development@kiraguvence.com',
      contactType: 'technical support',
      availableLanguage: ['Turkish', 'English'],
    },
  ],
  address: {
    '@type': 'PostalAddress',
    addressCountry: 'TR',
    addressLocality: 'Istanbul',
  },
  sameAs: [
    'https://kiraguvence.com',
  ],
};

const webAppJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: 'SecureLend',
  url: 'https://kiraguvence.com',
  applicationCategory: 'FinanceApplication',
  operatingSystem: 'Web, iOS, Android',
  description:
    'Kiraci, ev sahibi ve banka arasindaki kira odeme surecini dijital ortamda guvenle yonetin.',
  featureList: [
    'Dijital kira sozlesmesi',
    'Otomatik kira odeme takibi',
    'KPS kimlik dogrulama',
    'KMH (Konut Mortgage Hesabi) basvurusu',
    'Anlık bildirimler',
    'Mulk yonetimi',
  ],
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'TRY',
    description: 'Ucretsiz kayit ve temel ozellikler',
  },
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.8',
    ratingCount: '150',
    bestRating: '5',
  },
};

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'SecureLend nedir?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'SecureLend, kiraci ve ev sahibi arasindaki kira odeme surecini dijital ortamda guvenle yoneten bir fintech platformudur. Dijital sozlesme, otomatik odeme takibi ve KPS kimlik dogrulama ozellikleri sunar.',
      },
    },
    {
      '@type': 'Question',
      name: 'KMH (Konut Mortgage Hesabi) nedir?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'KMH, kiracilar icin ozel olarak tasarlanmis bir finansman hesabidir. Kira odemelerinizi duzenli olarak yapmanizi saglayan, banka destekli bir odeme sistemidir.',
      },
    },
    {
      '@type': 'Question',
      name: 'SecureLend ucretsiz mi?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Evet, SecureLend platformuna kayit olmak ve temel ozellikleri kullanmak tamamen ucretsizdir.',
      },
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body className="antialiased min-h-screen">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
